SELECT
	TRNF.TRNF_ID,
	TRNF.TRNF_FECHA,
	TRNF.TRNF_IMPORTE,
	TRNF.CLIE_ID_CLI2 AS 'CLIE_ID',
	CLIE.CLIE_NOMBRE AS 'CLIE_NOMBRE',
	CLIE.CONC_ID_CONC AS 'CLIE_CONCEPTO_ID',
	TRNF.CLIE_ID_CLIE AS 'PROV_ID',
	PROV.CLIE_NOMBRE AS 'PROV_NOMBRE',
	PROV.CONC_ID_CONC AS 'PROV_CONCEPTO_ID'
FROM
	VF_ENT_TRANSFERENCIA TRNF 
LEFT JOIN VF_ENT_CLIENTE PROV ON
	TRNF.CLIE_ID_CLIE = PROV.CLIE_ID
LEFT JOIN VF_ENT_CLIENTE CLIE ON
	TRNF.CLIE_ID_CLI2 = CLIE.CLIE_ID 
WHERE TRNF.TRNF_FECHA >  CONVERT(DATETIME, DATEADD(MONTH, -3, CONVERT(DATE, GETDATE())))